//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceTeam_Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public int MAHD { get; set; }
        public int MAHH { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
