//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceTeam_Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int MAHD { get; set; }
        public int MANV { get; set; }
        public int MACHINHANH { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string GHICHU { get; set; }
        public System.DateTime NGAYTAO { get; set; }
        public Nullable<decimal> TONGTIENHANG { get; set; }
        public Nullable<decimal> TONGTHUCTHU { get; set; }
    
        public virtual CHINHANH CHINHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
